export const getData = async () => {
  return [
    {
      id: 1,
      name: "McFlurry® with OREO® cookies",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-oreo-mcflurry-snack:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 2,
      name: "McFlurry® with M&M'S® Candies",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mm-mcflurry-snack:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 3,
      name: "Vanilla Cone",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-Reduced-Fat-Ice-Cream-Cone:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 4,
      name: "Chocolate Shake",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chocolate-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 5,
      name: "Vanilla Shake",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 6,
      name: "Strawberry Shake",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 7,
      name: "Hot Fudge Sundae",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hot-Fudge-Sundae:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 8,
      name: "Hot Caramel Sundae",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hot-Caramel-Sundae-1:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 9,
      name: "Baked Apple Pie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Baked-Hot-Apple-Pie-1:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 10,
      name: "Chocolate Chip Cookie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chocolate-Chip-Cookie-mcd:1-4-product-tile-desktop",
      price: 100,
      type: "mc_dessert_shakes",
    },
    {
      id: 11,
      name: "Minute Maid® Strawberry Watermelon Slushie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumStrawberryWatermelonSlushie_Glass_832x472:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 12,
      name: "Minute Maid® Tropical Mango Slushie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumTropicalMangoSlushie_Glass_832x472:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 13,
      name: "Coca-Cola®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Coca-Cola-Classic-Small-1:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 14,
      name: "Sprite®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sprite-Small:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 15,
      name: "Dr Pepper®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dr-Pepper-Small-1:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 16,
      name: "Fanta® Orange",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fanta-orange-1:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 17,
      name: "Diet Coke®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Diet-Coke-Small-1:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 18,
      name: "Hi-C® Orange Lavaburst®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hi-c-lavaburst:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 19,
      name: "Sweet Tea",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-drink:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 20,
      name: "Unsweetened Iced Tea",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-unsweetened:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 21,
      name: "DASANI® Water",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dasani-Water:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 22,
      name: "Minute Maid® Orange Juice",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Minute-Maid-Orange-Juice-Medium-1:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 23,
      name: "Honest Kids® Appley Ever After® Organic Juice Drink",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-appley-ever-after:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 24,
      name: "1% Low Fat Milk Jug",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-1-Low-Fat-Milk-Jug:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 25,
      name: "Reduced Sugar* Low Fat Chocolate Milk Jug",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Fat-Free-Chocolate-Milk-Jug:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 26,
      name: "Strawberry Banana Smoothie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-Banana-Smoothie-Medium:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 27,
      name: "Mango Pineapple Smoothie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Mango-Pineapple-Smoothie-Small:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 28,
      name: "Hot Chocolate",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Hot-Chocolate-Medium:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 29,
      name: "Hot Tea",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hot-tea:1-4-product-tile-desktop",
      price: 2500,
      type: "mc_beverages",
    },
    {
      id: 30,
      name: "Bacon, Egg  & Cheese Biscuit",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Bacon-Egg-Cheese-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 31,
      name: "Egg McMuffin®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Egg-McMuffin-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 32,
      name: "Sausage McMuffin®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 33,
      name: "Sausage McMuffin® with Egg",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin-with-Egg:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 34,
      name: "Sausage Biscuit",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 35,
      name: "Sausage Biscuit  with Egg",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-with-Egg-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 36,
      name: "Bacon, Egg & Cheese McGriddles®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Bacon-Egg-Cheese-McGriddles:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 37,
      name: "Sausage McGriddles®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McGriddles:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 38,
      name: "Sausage, Egg & Cheese McGriddles®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Egg-Cheese-McGriddles-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 39,
      name: "Big Breakfast®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/s-mcdonalds-Big-Breakfast-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 40,
      name: "Big Breakfast® with Hotcakes",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Big-Breakfast-with-Hotcakes-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 41,
      name: "Hotcakes",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hotcakes:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 42,
      name: "Hotcakes and Sausage",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hotcakes-and-Sausage:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 43,
      name: "Sausage Burrito",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Burrito-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 44,
      name: "Hash Browns",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-HASH-BROWNS-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 45,
      name: "Fruit & Maple Oatmeal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Fruit-Maple-Oatmeal-1:1-4-product-tile-desktop",
      price: 3100,
      type: "mc_breakfast",
    },
    {
      id: 46,
      name: "Big Mac®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Big-Mac-1:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 47,
      name: "Quarter Pounder®* with Cheese",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Quarter-Pounder-with-Cheese-1:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 48,
      name: "Double Quarter Pounder®* with Cheese",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Double-Quarter-Pounder-with-Cheese-1:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 49,
      name: "Quarter Pounder®* with Cheese Deluxe",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-qpc-deluxe-burger:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 50,
      name: "McDouble®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McDouble-1:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 51,
      name: "Quarter Pounder®* with Cheese Bacon",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-qpc-bacon-burger:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 52,
      name: "Cheeseburger",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Cheeseburger-1:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 53,
      name: "Double Cheeseburger",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Double-Cheeseburger-1:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 54,
      name: "Hamburger: The Classic McDonald's Burger",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hamburger:1-4-product-tile-desktop",
      price: 4570,
      type: "mc_burgers",
    },
    {
      id: 55,
      name: "Spicy Deluxe Crispy Chicken Sandwich",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-spicy-deluxe-crispy-chicken-sandwich:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 56,
      name: "Crispy Chicken Sandwich",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-crispy-chicken-sandwich:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 57,
      name: "Spicy Crispy Chicken Sandwich",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-spicy-crispy-chicken-sandwich:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 58,
      name: "Deluxe Crispy Chicken Sandwich",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-deluxe-crispy-chicken-sandwich:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 59,
      name: "Chicken McNuggets®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chicken-McNuggets-4pc-1:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 60,
      name: "McChicken®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McChicken-1:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 61,
      name: "Filet-O-Fish®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Filet-O-Fish-1:1-4-product-tile-desktop",
      price: 5700,
      type: "mc_chicken_sandwiches",
    },
    {
      id: 62,
      name: "Big Mac® Combo Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Big-Mac-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 63,
      name: "Cheeseburger Combo Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-2-Cheeseburger-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 64,
      name: "Quarter Pounder®* with Cheese Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Quarter-Pounder-with-Cheese-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 65,
      name: "Double Quarter Pounder®* with Cheese Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Double-Quarter-Pounder-with-Cheese-Extra-Value-Meals-combo:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 66,
      name: "Crispy Chicken Sandwich Combo Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-crispy-chicken-sandwich-meal:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 67,
      name: "Spicy Crispy Chicken Sandwich Combo Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-spicy-crispy-chicken-sandwich-meal-combo:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 68,
      name: "Deluxe Crispy Chicken Sandwich Combo Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-deluxe-crispy-chicken-sandwich-meal:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 69,
      name: "10 piece Chicken McNuggets® Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Chicken-McNuggets-10-piece-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 70,
      name: "Filet-O-Fish® Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Filet-O-Fish-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 71,
      name: "Egg McMuffin® Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Egg-McMuffin-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 72,
      name: "Sausage McMuffin® with Egg Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-McMuffin-with-Egg-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 73,
      name: "Sausage Biscuit with Egg Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-Biscuit-with-Egg-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 74,
      name: "Bacon, Egg &amp; Cheese Biscuit Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Bacon-Egg-Cheese-Biscuit-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 75,
      name: "Bacon, Egg &amp; Cheese McGriddles® Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Bacon-Egg-Cheese-McGriddles-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 76,
      name: "Sausage, Egg &amp; Cheese McGriddles® Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-Egg-Cheese-McGriddles-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 77,
      name: "Sausage McGriddles® Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-McGriddles-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 78,
      name: "Sausage Burrito Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-Burrito-2-Extra-Value-Meals:1-4-product-tile-desktop",
      price: 6100,
      type: "mc_combo_meal",
    },
    {
      id: 79,
      name: "Hamburger Happy Meal®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Hamburger:1-4-product-tile-desktop",
      price: 27000,
      type: "mc_happy_meal",
    },
    {
      id: 80,
      name: "4 Piece Chicken McNuggets® Happy Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Chicken-McNuggets:1-4-product-tile-desktop",
      price: 27000,
      type: "mc_happy_meal",
    },
    {
      id: 81,
      name: "6 Piece Chicken McNuggets® Happy Meal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-Chicken-McNuggets-Mighty-Kids-Meals:1-4-product-tile-desktop",
      price: 27000,
      type: "mc_happy_meal",
    },
    {
      id: 82,
      name: "Apple Fritter",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-apple-fritter-bakery:1-4-product-tile-desktop",
      price: 3700,
      type: "mc_cafe_bakery",
    },
    {
      id: 83,
      name: "Blueberry Muffin",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-blueberry-muffin-bakery-mcd:1-4-product-tile-desktop",
      price: 3700,
      type: "mc_cafe_bakery",
    },
    {
      id: 84,
      name: "Cinnamon Roll with Cream Cheese Icing",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-cinnamon-roll-mcbakery:1-4-product-tile-desktop",
      price: 3700,
      type: "mc_cafe_bakery",
    },
    {
      id: 85,
      name: "World Famous Fries®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fries-small:1-4-product-tile-desktop",
      price: 4100,
      type: "mc_snacks_sides",
    },
    {
      id: 86,
      name: "Apple Slices",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Apple-Slices:1-4-product-tile-desktop",
      price: 4100,
      type: "mc_snacks_sides",
    },
    {
      id: 87,
      name: "Caramel Macchiato",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-caramel-macchiato:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 88,
      name: "Iced Caramel Macchiato",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-caramel-macchiato-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 89,
      name: "Cappuccino",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-cappuccino-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 90,
      name: "Caramel Cappuccino",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-caramel-cappuccino:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 91,
      name: "French Vanilla Cappuccino",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-vanilla-cappuccino:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 92,
      name: "Mocha",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Mocha-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 93,
      name: "Iced Mocha",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Iced-Mocha-Medium-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 94,
      name: "Latte",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Latte-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 95,
      name: "Iced Latte",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-latte-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 96,
      name: "Caramel Latte",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Caramel-Latte-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 97,
      name: "Iced Caramel Latte",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-caramel-latte:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 98,
      name: "French Vanilla Latte",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Vanilla-Latte-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 99,
      name: "Iced French Vanilla Latte",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-french-vanilla-latte-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 100,
      name: "Americano",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-americano-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 101,
      name: "Premium Roast Coffee",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Coffee-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 102,
      name: "Iced Coffee",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Premium-Roast-Iced-Coffee-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 103,
      name: "Iced Caramel Coffee",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Caramel-Iced-Coffee:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 104,
      name: "Iced French Vanilla Coffee",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-Iced-Coffee:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 105,
      name: "Caramel Frappé",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Frappe-Caramel-Medium-1:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 106,
      name: "Mocha Frappé",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Frappe-Mocha-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 107,
      name: "Hot Chocolate",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Hot-Chocolate-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 108,
      name: "Strawberry Banana Smoothie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-Banana-Smoothie-Medium:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
    {
      id: 109,
      name: "Mango Pineapple Smoothie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Mango-Pineapple-Smoothie-Small:1-4-product-tile-desktop",
      price: 7500,
      type: "mc_cafe_drinks",
    },
  ];
};
