export const getData = async () => {
  return [
    {
      id: 1,
      name: "McFlurry® with OREO® cookies",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-oreo-mcflurry-snack:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 2,
      name: "McFlurry® with M&amp;M'S® Candies",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mm-mcflurry-snack:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 3,
      name: "Vanilla Cone",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-Reduced-Fat-Ice-Cream-Cone:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 4,
      name: "Chocolate Shake",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chocolate-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 5,
      name: "Vanilla Shake",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 6,
      name: "Strawberry Shake",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 7,
      name: "Hot Fudge Sundae",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hot-Fudge-Sundae:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 8,
      name: "Hot Caramel Sundae",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hot-Caramel-Sundae-1:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 9,
      name: "Baked Apple Pie",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Baked-Hot-Apple-Pie-1:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 10,
      name: "Chocolate Chip Cookie",
      price: 100,
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chocolate-Chip-Cookie-mcd:1-4-product-tile-desktop",
      type: "Desserts & Shakes",
    },
    {
      id: 11,
      type: "Beverages",
      name: "Minute Maid® Strawberry Watermelon Slushie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumStrawberryWatermelonSlushie_Glass_832x472:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 12,
      type: "Beverages",
      name: "Minute Maid® Tropical Mango Slushie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumTropicalMangoSlushie_Glass_832x472:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 13,
      type: "Beverages",
      name: "Coca-Cola®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Coca-Cola-Classic-Small-1:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 14,
      type: "Beverages",
      name: "Sprite®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sprite-Small:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 15,
      type: "Beverages",
      name: "Dr Pepper®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dr-Pepper-Small-1:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 16,
      type: "Beverages",
      name: "Fanta® Orange",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fanta-orange-1:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 17,
      type: "Beverages",
      name: "Diet Coke®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Diet-Coke-Small-1:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 18,
      type: "Beverages",
      name: "Hi-C® Orange Lavaburst®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hi-c-lavaburst:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 19,
      type: "Beverages",
      name: "Sweet Tea",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-drink:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 20,
      type: "Beverages",
      name: "Unsweetened Iced Tea",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-unsweetened:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 21,
      type: "Beverages",
      name: "DASANI® Water",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dasani-Water:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 22,
      type: "Beverages",
      name: "Minute Maid® Orange Juice",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Minute-Maid-Orange-Juice-Medium-1:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 23,
      type: "Beverages",
      name: "Honest Kids® Appley Ever After® Organic Juice Drink",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-appley-ever-after:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 24,
      type: "Beverages",
      name: "1% Low Fat Milk Jug",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-1-Low-Fat-Milk-Jug:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 25,
      type: "Beverages",
      name: "Reduced Sugar* Low Fat Chocolate Milk Jug",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Fat-Free-Chocolate-Milk-Jug:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 26,
      type: "Beverages",
      name: "Strawberry Banana Smoothie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-Banana-Smoothie-Medium:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 27,
      type: "Beverages",
      name: "Mango Pineapple Smoothie",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Mango-Pineapple-Smoothie-Small:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 28,
      type: "Beverages",
      name: "Hot Chocolate",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Hot-Chocolate-Medium:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 29,
      type: "Beverages",
      name: "Hot Tea",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hot-tea:1-4-product-tile-desktop",
      price: 2500,
    },
    {
      id: 30,
      type: "Breakfast",
      name: "Bacon, Egg  & Cheese Biscuit",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Bacon-Egg-Cheese-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 31,
      type: "Breakfast",
      name: "Egg McMuffin®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Egg-McMuffin-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 32,
      type: "Breakfast",
      name: "Sausage McMuffin®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 33,
      type: "Breakfast",
      name: "Sausage McMuffin® with Egg",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin-with-Egg:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 34,
      type: "Breakfast",
      name: "Sausage Biscuit",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 35,
      type: "Breakfast",
      name: "Sausage Biscuit  with Egg",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-with-Egg-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 36,
      type: "Breakfast",
      name: "Bacon, Egg & Cheese McGriddles®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Bacon-Egg-Cheese-McGriddles:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 37,
      type: "Breakfast",
      name: "Sausage McGriddles®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McGriddles:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 38,
      type: "Breakfast",
      name: "Sausage, Egg & Cheese McGriddles®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Egg-Cheese-McGriddles-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 39,
      type: "Breakfast",
      name: "Big Breakfast®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/s-mcdonalds-Big-Breakfast-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 40,
      type: "Breakfast",
      name: "Big Breakfast® with Hotcakes",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Big-Breakfast-with-Hotcakes-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 41,
      type: "Breakfast",
      name: "Hotcakes",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hotcakes:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 42,
      type: "Breakfast",
      name: "Hotcakes and Sausage",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hotcakes-and-Sausage:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 43,
      type: "Breakfast",
      name: "Sausage Burrito",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Burrito-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 44,
      type: "Breakfast",
      name: "Hash Browns",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-HASH-BROWNS-1:1-4-product-tile-desktop",
      price: 3100,
    },
    {
      id: 45,
      type: "Breakfast",
      name: "Fruit & Maple Oatmeal",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Fruit-Maple-Oatmeal-1:1-4-product-tile-desktop",
      price: 3100,
    },

    {
      id: 46,
      type: "Burgers",
      name: "Big Mac®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Big-Mac-1:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 47,
      type: "Burgers",
      name: "Quarter Pounder®* with Cheese",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Quarter-Pounder-with-Cheese-1:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 48,
      type: "Burgers",
      name: "Double Quarter Pounder®* with Cheese",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Double-Quarter-Pounder-with-Cheese-1:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 49,
      type: "Burgers",
      name: "Quarter Pounder®* with Cheese Deluxe",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-qpc-deluxe-burger:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 50,
      type: "Burgers",
      name: "McDouble®",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McDouble-1:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 51,
      type: "Burgers",
      name: "Quarter Pounder®* with Cheese Bacon",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-qpc-bacon-burger:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 52,
      type: "Burgers",
      name: "Cheeseburger",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Cheeseburger-1:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 53,
      type: "Burgers",
      name: "Double Cheeseburger",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Double-Cheeseburger-1:1-4-product-tile-desktop",
      price: 4570,
    },
    {
      id: 54,
      type: "Burgers",
      name: "Hamburger: The Classic McDonald's Burger",
      img: "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hamburger:1-4-product-tile-desktop",
      price: 4570,
    },
  ];
};
